spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : dhkd2303
  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
       format_sql : true
  auth:
    jwt:
      secret_key: baby-on-top-jwt-secret-key-token
      access_time: 3600000
      refresh_time: 864000000
#  main:
#    allow-bean-definition-overriding : true
#    allow-circular-references: true